

CREATE USER MORASOL
  IDENTIFIED BY MORASOL
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for MORASOL 
  GRANT EXP_FULL_DATABASE TO MORASOL;
  GRANT IMP_FULL_DATABASE TO MORASOL;
  GRANT CONNECT TO MORASOL;
  ALTER USER MORASOL DEFAULT ROLE ALL;
  -- 4 System Privileges for MORASOL 
  GRANT UNLIMITED TABLESPACE TO MORASOL;
  GRANT DEBUG CONNECT SESSION TO MORASOL;
  GRANT SELECT ANY TABLE TO MORASOL;
  GRANT DEBUG ANY PROCEDURE TO MORASOL;
  


  *******************************************************************************************************

CREATE TABLE TRESE
(
  TRESE_HOTEL     VARCHAR2(15 BYTE),
  TRESE_CODI      NUMBER,
  TRESE_ANCI      NUMBER,
  TRESE_DESGLOSE  NUMBER,
  TRESE_HOTE      VARCHAR2(30 BYTE),
  TRESE_DACR      DATE,
  TRESE_CLIE      VARCHAR2(50 BYTE),
  TRESE_TTOO      VARCHAR2(50 BYTE),
  TRESE_AGENCIA      VARCHAR2(50 BYTE),
  TRESE_DAEN      DATE,
  TRESE_DASA      DATE,
  TNACI_CODI      VARCHAR2(3 BYTE),
  TRESE_THABRESE  VARCHAR2(10 BYTE),
  TRESE_THABOCUP  VARCHAR2(10 BYTE),
  TRESE_TREG      VARCHAR2(5 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TRESE_PK ON TRESE
(TRESE_HOTEL, TRESE_CODI, TRESE_ANCI, TRESE_DESGLOSE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TRESE ADD (
  CONSTRAINT TRESE_PK
  PRIMARY KEY
  (TRESE_HOTEL, TRESE_CODI, TRESE_ANCI, TRESE_DESGLOSE)
  USING INDEX TRESE_PK);




  -- *****************************************************************************************

CREATE TABLE MORASOL.TENTIDADES
(
  HOTEL     VARCHAR2(25),
  TTOO       VARCHAR2(50),
  AGENCIA    VARCHAR2(50),
  CLIENTE VARCHAR(25),
  ENTI_CODI  VARCHAR2(8),
  OPER_CODI  VARCHAR2(8)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;
